### ISSUE TITLE
App does not update risk state GUI on Samsung S5 Mini

### ISSUE THREAD

**Issue by AnOtherMuenchner** [corona-warn-app/cwa-app-android#1817]
Should you experience similar issue, have a look here:
**EN** https://www.coronawarn.app/en/faq/#no_risk_update
**DE** https://www.coronawarn.app/de/faq/#no_risk_update

---

On my Galaxy S5 mini, the app does not update the GUI displaying the risk state. It states, the last actualisation has been done on 2020-11-24. However, there are later update, e.g. yesterday and today.

When I look into the log on the mobile, I can also see that there has been calculcation of risk state.

---
Internal Tracking ID:  [EXPOSUREAPP-4087](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4087)

**Comment by MikeMcC399** [comment]
@AnOtherMuenchner 
This has also been reported in https://github.com/corona-warn-app/cwa-app-android/issues/1459#issuecomment-739418707 .

Could you share your exposure log?

Go to Settings > Google > COVID-19 exposure notifications > Exposure checks
Use the three dot menu to Export exposure checks.
Rename the file extension from .json to .txt then attach the file to the post.
or for German UI:
Einstellungen > Google > COVID-19-Benachrichtigungen > Überprüfung auf mögliche Begegnungen
Drei-Punkte-Menü aufrufen und "Überprüfungen exportieren" auswählen.

Also your Android version and CWA app version would be helpful to know.

**Comment by thomasaugsten** [comment]
@AnOtherMuenchner Can you please share some additional information about your phone and android build. Can you elaborate how and which mobile data/wifi Connection you are using. As well is the app in battery optimization or not.

**Comment by AnOtherMuenchner** [comment]
Here are the information:

- Phone: Samsung S5 mini
- Android Version: 6.0.1
- Kernel-Version: 3.4.39-13885706
- Buildnumber: MMB29K.G800FXXU1CRG3

Version of Corona-WarnApp  is 1.7.1.

Connection via Wifi.

I do not use this mobile every day. So there are some holes in the check log.

[all-exposure-checks.txt](https://github.com/corona-warn-app/cwa-app-android/files/5649222/all-exposure-checks.txt)

**Comment by MikeMcC399** [comment]
@AnOtherMuenchner 

> I do not use this mobile every day. So there are some holes in the check log.

When you are not using the mobile device, what state is it in? Is it simply switched off?

> On my Galaxy S5 mini, the app does not update the GUI displaying the risk state. It states, the last actualisation has been done on 2020-11-24. However, there are later update, e.g. yesterday and today.

Thank you for providing the exposure log! On Nov 24, 2020, which you say is the day shown in CWA as the last update, there are 6 attempts logged, all around the same time from 11:17 to 11:26.

Can you correlate the times on Dec 5 (yesterday) 13:41 and Dec 6 (today) 10:26 with any event like switching on the device or opening the app?

  | timestamp | keyCount | matchesCount | appName | hash
-- | -- | -- | -- | -- | --
  | 6.   Dezember 2020, 10:26 | 277384 | 0 | Corona-Warn | wPI41GzenV44L7BmwAfPmwKSYT/+0/cSLScgDGEGGXo=
  | 5. Dezember 2020, 13:41 | 275135 | 0 | Corona-Warn | KQ4v1i+nHel/84QwJwiPPapRatdyWyhubhlsiEtMZo4=
  | 1.   Dezember 2020, 07:14 | 273450 | 0 | Corona-Warn | 1ZALbzWBKWogbSiWacZV0KMkxoKRhFpGG8WZjv3k4dg=
  | 1. Dezember 2020, 07:12 | 273450 | 0 | Corona-Warn | 1ZALbzWBKWogbSiWacZV0KMkxoKRhFpGG8WZjv3k4dg=
  | 30.   November 2020, 06:00 | 230009 | 0 | Corona-Warn | tW2zelNXcSKk0EBzLDZLQtq5AgXqXTKH8tuoGyae4Kg=
  | 24. November 2020, 11:26 | 306402 | 0 | Corona-Warn | g/U5c9SlzUI9mNTia1rzDiuYsUK1Vdno18A77XDlIMo=
  | 24.   November 2020, 11:23 | 306402 | 0 | Corona-Warn | g/U5c9SlzUI9mNTia1rzDiuYsUK1Vdno18A77XDlIMo=
  | 24. November 2020, 11:21 | 306402 | 0 | Corona-Warn | g/U5c9SlzUI9mNTia1rzDiuYsUK1Vdno18A77XDlIMo=
  | 24.   November 2020, 11:19 | 306402 | 0 | Corona-Warn | g/U5c9SlzUI9mNTia1rzDiuYsUK1Vdno18A77XDlIMo=
  | 24. November 2020, 11:19 | 306402 | 0 | Corona-Warn | g/U5c9SlzUI9mNTia1rzDiuYsUK1Vdno18A77XDlIMo=
  | 24.   November 2020, 11:17 | 306402 | 0 | Corona-Warn | g/U5c9SlzUI9mNTia1rzDiuYsUK1Vdno18A77XDlIMo=
  | 23. November 2020, 18:30 | 306491 | 0 | Corona-Warn | rdoZwWL0jRHNAq+uT4jWDt1k1YRQ7xVSmOlJXlhjk0Q=
  | 23.   November 2020, 18:25 | 306491 | 0 | Corona-Warn | rdoZwWL0jRHNAq+uT4jWDt1k1YRQ7xVSmOlJXlhjk0Q=
  | 23. November 2020, 18:19 | 306491 | 0 | Corona-Warn | rdoZwWL0jRHNAq+uT4jWDt1k1YRQ7xVSmOlJXlhjk0Q=
  | 23.   November 2020, 18:19 | 306491 | 0 | Corona-Warn | rdoZwWL0jRHNAq+uT4jWDt1k1YRQ7xVSmOlJXlhjk0Q=
  | 23. November 2020, 18:17 | 306491 | 0 | Corona-Warn | rdoZwWL0jRHNAq+uT4jWDt1k1YRQ7xVSmOlJXlhjk0Q=
  | 23.   November 2020, 18:15 | 306491 | 0 | Corona-Warn | rdoZwWL0jRHNAq+uT4jWDt1k1YRQ7xVSmOlJXlhjk0Q=

**Comment by AnOtherMuenchner** [comment]
@MikeMcC399 

Normally, the device is switched off. The last days it has been in offline-mode during the night.

For the checks on december 5 and 6: According to the log on my Fritzbox, the mobile has been connected to Wifi on december 5 at 13:32, on december 6 at 10:22.

**Comment by MikeMcC399** [comment]
This is for the issue reported by @schneik1 in https://github.com/corona-warn-app/cwa-app-android/issues/1459#issuecomment-739418707 

@schneik1 wrote:
>Hallo,
here the info:
Phone: Samsung S5 mini SM-G800F
Android: 6.0.1
Kernal:3.4.39-13885706
Buildnumber:MMB29K,G800FXXU1CRG3
Provider is O2
>
>The Corona-App is Version 1.7.1
The Phone is used every day.
>
>I.e. yesterday and today 90% connected via home-WLAN.

So now there are three problems:
1. Google update timestamp differs from CWA last update timestamp.
2. CWA app updates only once a day even though you say you were connected via WiFi.
3. The exposure log file is not getting aged out after nominally 14 days (in practice it is actually 16 days). Your logs go back about 65 days.

The [exposure log file](https://github.com/corona-warn-app/cwa-app-android/files/5649340/all-exposure-checks.txt) shows 300 entries, which is the maximum that Google allows (it used to stop at a maximum of 100 entries). The earliest entry is from Oct 9, 2020 where there are 6 entries at the same time. Multiple attempts are similar to what @AnOtherMuenchner 's logs are also showing.

Here are the most recent:

_ | timestamp | keyCount | matchesCount | appName | hash
-- | -- | -- | -- | -- | --
  | 6. Dezember   2020, 01:20 | 277384 | 0 | Corona-Warn | JFH1fSbNu2OrnA1bQn+iaQaczebNX1BvO+1KxBtod2M=
  | 5. Dezember 2020, 01:29 | 275135 | 0 | Corona-Warn | zxBpCAJZYrLT3wewjCPhaKvmr+3feBg+qGw8JzgSqVQ=
  | 4. Dezember   2020, 01:38 | 274440 | 0 | Corona-Warn | 6dioLWXMYozbgQdJtI99a6cuVpGHYCMXi/QgqM50up4=
  | 3. Dezember 2020, 02:01 | 276324 | 0 | Corona-Warn | Euq/5+DcEaHm4i1cTCRM1Q57XqbBKjqmphctASTnczM=
  | 2. Dezember   2020, 03:11 | 276750 | 0 | Corona-Warn | DYJBtelVp6iCDRcVDBshfFKrs1JVvo9+pTPlbQbLVvw=
  | 1. Dezember 2020, 01:48 | 273450 | 0 | Corona-Warn | haj+33N9Lm8N9vlvnOOVDKo/YX/ONDZgwKOgTOAzD5M=
  | 30. November   2020, 02:26 | 277797 | 0 | Corona-Warn | hQOLFeCj3KhU+dCzhB56WaYgQTVpKWEd4Gqp1aHaANI=
  | 29. November 2020, 01:19 | 279801 | 0 | Corona-Warn | h93NvA6gba+OHEtZ7ocvhx+XC6wDEohJyz8refM/qBQ=
  | 28. November   2020, 02:07 | 281430 | 0 | Corona-Warn | ZNRmgblPYjfUKE4ZwTZaazM4VC7LBc4xzi2sC0VLyHs=
  | 27. November 2020, 01:04 | 295102 | 0 | Corona-Warn | tDr0ecda8McCNZOMawY1W0Izv2L+thLCpvB29tHEul4=
  | 26. November   2020, 01:31 | 295102 | 0 | Corona-Warn | tDr0ecda8McCNZOMawY1W0Izv2L+thLCpvB29tHEul4=
  | 25. November 2020, 02:37 | 300595 | 0 | Corona-Warn | KTrZypvaL0JOjwz0WthR/zwlNf1kL6WWqnJnVQUNo7w=
  | 24. November   2020, 01:14 | 306402 | 0 | Corona-Warn | ttym0+ALhZRVGEFfSkMgLakVR1YyFABTLO9Po1hJ0uI=
  | 23. November 2020, 01:06 | 311179 | 0 | Corona-Warn | QEK5sxjZtm40WwgVxuIfCBiC8qjdfLKQ7LvYgUYS7ks=
  | 22. November   2020, 02:55 | 311179 | 0 | Corona-Warn | QEK5sxjZtm40WwgVxuIfCBiC8qjdfLKQ7LvYgUYS7ks=
  | 22. November 2020, 02:51 | 311179 | 0 | Corona-Warn | QEK5sxjZtm40WwgVxuIfCBiC8qjdfLKQ7LvYgUYS7ks=
  | 21. November   2020, 02:14 | 315100 | 0 | Corona-Warn | AtIaMebISwRbLlELRuMlOlHrVcuwKn1DuvDB4W5l1T8=

**Comment by thomasaugsten** [comment]
Is there a SIM card installed?

**Comment by MikeMcC399** [comment]
@schneik1
Is your device rooted?

**Comment by schneik1** [comment]
Hallo all,
the device is not rooted.
Yes a O2 Sim-card is installed.

**Comment by IT-Cons-Max** [comment]
Same behavior on my device, therefore some additional information, which might help:

Phone: Samsung S5 Neo SM-G903F
Android: 6.0.1
Kernel: 3.10.61-^4251224
Buildno: MMB29K.G903FXXU2BRH2
CWA-version: 1.7.1
Google version: 18204516000
Smartphone is not rooted, internet access mostly via WLAN, SIM-card installed

The Phone is used daily, but **switched off every evening and switched on in the morning** between 7 am and 9 am.

Missing updates since 30. Nov. 20 after installing CWA version 1.7.1 on 28. Nov. 20 in the evening (1.7.0 crashed (#1727), but 1.6.x worked)

**Screenshots as of 06. Dec. 09:20:**

![Screenshot_20201206-091952-klein1](https://user-images.githubusercontent.com/75634622/101400991-fbdfca80-38d1-11eb-897b-504f35e1e4d5.jpg)

![Screenshot_20201206-092038-klein](https://user-images.githubusercontent.com/75634622/101400821-bfac6a00-38d1-11eb-956a-40e76e3bae58.jpg)

The risk status was only updated, when an exposure log was downloaded after noon.

Date___________log-timestamp
29. Nov. 2020	13:11   processed
30. Nov. 2020	07:49 
01. Dec. 2020	07:47
02. Dec. 2020	12:50   processed
03. Dec. 2020	07:44
04. Dec. 2020	08:07
05. Dec. 2020	08:18
06. Dec. 2020	13:17   processed
07. Dec. 2020	07:25

At days, when exposure logs were processed, the smartphone was at least two days switched on around 9 am. When smartphone was switched on earlier (before 08:30 am) CWA always discards daily and previous logs with timestamps in the morning.

As mentioned by @MikeMcC399 there is only exactly one new exposure log per day instead of multiple (with version 1.6.x there were up to four logs with different timestamps, which might have been a bug). The oldest exposure log shows timestamp 22. Nov. The content of my exposure logs (no. keys) is identical to above mentioned logs.
[all-exposure-checks.json.txt](https://github.com/corona-warn-app/cwa-app-android/files/5655050/all-exposure-checks.json.txt)

The number of contacts shown in Settings -> Google was decreased by 1 every day the update was ignored by CWA and increased by 1, if the update was processed. 

One new observation (perhaps a different topic): 
Today (07. Dec. 20) the screen in Seetings -> Google with the number of contacts wasn’t shown anymore ("Überprüfung auf mögliche Begegnungen" etc.). In the new screen exposure logs (Text in the middle: "Covid-19 Benachrichtigungen stützen sich...") can only be accessed via 3-dot-menu right on top.

**Comment by dsarkar** [comment]
@IT-Cons-Max. Thanks for reporting in such detail. We will forward this information to the developers. Best regards, DS

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@IT-Cons-Max 
> One new observation (perhaps a different topic):
Today (07. Dec. 20) the screen in Seetings -> Google with the number of contacts wasn’t shown anymore ("Überprüfung auf mögliche Begegnungen" etc.). In the new screen exposure logs (Text in the middle: "Covid-19 Benachrichtigungen stützen sich...") can only be accessed via 3-dot-menu right on top.

It's good that you have provided so much information for the developers, so we can leave that part for them to respond.

For the benefit of the community could you expand on your last topic (quoted above), which I didn't really understand. Perhaps you could add some screenshots? Google doesn't show the number of contacts, it only shows the number of exposure checks and the number of exposure matches. Also I couldn't find the text "Covid-19 Benachrichtigungen stützen sich..." anywhere I looked. It sounded a bit like "COVID-19-Benachrichtigungen" was no longer available in the Einstellungen > Google menu, which would be a sign that there is something wrong with the installation of the Google Exposure Notifications System in Google Play services.

**Comment by IT-Cons-Max** [comment]
@MikeMcC399: you're right, you couldn't find the text because a hyphen was missing in "COVID-19**-**Benachrichtigungen stützen sich...", but the setting itsself was available and active (see newly added screenshot). And I have to get a bit more familiar with the correct wording (e.g. "number of exposure checks" instead of "number of contacts").

![Screenshot_20201207-210707-klein](https://user-images.githubusercontent.com/75634622/101464851-7e52a380-393f-11eb-89d6-f4b8c7812552.jpg)

Anyway, yesterday at 22:0**5** a new exposure log was downloaded and the update was processed. CWA-display of update risk status showed 22:0**3** (two minutes time difference to log timestamp?). Also in Settings -> Google menu the strange screen was gone afterwards and the familiar display of "Überprüfung auf mögliche Begegnungen..." was back again.

Nevertheless the original issue is still present:
Today (08. Dec. 20) the latest exposure log with timestamp 07:57 was skipped again by CWA. According to CWA the last update was "Yesterday, 22:03". Again the early morning exposure log was discarded by CWA as the days before.

**Comment by MikeMcC399** [comment]
@IT-Cons-Max 
Thank you very much for the screen shot! That clarifies it for me, except that I have never seen this exact screen before and I don't know how to reproduce making it appear, so that is a mystery! It may be part of the problem. I don't have Android 6, so there is a small possibility that the screen might only appear on that version.

Regarding the difference in timestamps, this is a known issue see https://github.com/corona-warn-app/cwa-app-android/issues/948. Well spotted, but this is nothing to worry about right now

**Comment by sjnfr** [comment]
Same problem here.

Phone: Samsung Galaxy S5 Mini, SM-G800F
Android: 6.0.1
Kernel: 3.4.39-13885706
Buildno: MMB29K.G800FXXU1CRG4
CWA-version: 1.7.1
Google version: 18204516000
Smartphone is not rooted, internet access mostly via WLAN, SIM-card installed.

Last risk update was Friday, the 11th of December. When I take a look in my Google Account on my phone, obviously the App did still check for contacts even the days after the 11th and after it displayed me the last update on my risk status. I therefore called the Hotline, they first suggested me to turn on GPS and Bluetooth for the risk update (which, from my basic knowledge of IT-stuff isn't necessary for the contact-check-up of the last 14 days). So later that day, I called the hotline again which suggested me to reset the App (I didn't uninstall it, my contacts are still visible in the Google-Account). But that didn't change anything.

If you need any further information, please let me know.

Thank you!

**Comment by dsarkar** [comment]
Good morning @sjnfr! We will forward this information to the developers. Best regards, DS

---
Corona-Warn-App Open Source Team

**Comment by sjnfr** [comment]
Thanks. 

Surprisingly, the App updated my risk-status yesterday evening (automatically), now the screen is green again and not grey anymore. It says "Risiko-Ermittlung war für 2 der letzten 14 Tage aktiv". Im wondering why, because the Risikoermittlung was used nearly daily over the last two weeks. Most likely this is because I deleted my data in the App (not the movement Data, Anwendung zurückgesetzt) after the Hotline told me to do so. But then, my movement data from the last 14 days should still be recognised by the App, right? 

Just wanted to let you know.

**Comment by MikeMcC399** [comment]
@sjnfr 
>Surprisingly, the App updated my risk-status yesterday evening (automatically), now the screen is green again and not grey anymore. It says "Risiko-Ermittlung war für 2 der letzten 14 Tage aktiv". Im wondering why, because the Risikoermittlung was used nearly daily over the last two weeks. Most likely this is because I deleted my data in the App (not the movement Data, Anwendung zurückgesetzt) after the Hotline told me to do so. But then, my movement data from the last 14 days should still be recognised by the App, right?

When you reset the CWA app it clears CWA's memory of when it was running, so it starts the clock from 0 again. This only affects the status display in CWA. 

The Google Exposure Notification System's Rolling Proximity Identifiers (RPIs) are not deleted by resetting CWA in the app, so CWA can continue to check exposures against keys collected on previous days. Only uninstalling CWA (if it is the only COVID-19 app installed), or deleting CWA's data through Android storage commands, will delete the keys and history. So don't do that unless you can avoid it.

**Comment by sjnfr** [comment]
Alright, thank you very much!

**Comment by AnOtherMuenchner** [comment]
Yesterday I got an update for my phone's firmware (the first update after long time) and after this update, the CWA updated its risk state calculation from 2020-11-24 to 2020-12-17.

**Comment by AnOtherMuenchner** [comment]
Information for the update:

* Android version: 6.0.1
* New kernel version is 3.4.39-13885706 with date 2020-11-26  15:49 KST.
* Build number: MMB29K.G800FXXU1CTK1

I do not find the release notes anymore.

**Comment by MikeMcC399** [comment]
@AnOtherMuenchner 
> I do not find the release notes anymore.

On some Samsung Galaxy models you can select
Settings > Software update > Last update
which may have a link to the Samsung site, such as:

https://doc.samsungmobile.com/SM-G800F/DBT/doc.html

That may be the right link for your device. If it is, it doesn't say very much except:
"The security of your device has been improved."

**Comment by IT-Cons-Max** [comment]
@AnOtherMuenchner: Thank you for sharing this interesting news.
I just called the Samsung support regarding a firmware update for my Galaxy S5 neo (SM-903F). They didn't even know that there was a new version released for Galaxy S5 mini.
So I have to wait either for a fix in CWA or a firmware update. Hopefully at least one of these will happen soon. The current situation is really annoying.

**Comment by sjnfr** [comment]
> 
> 
> @AnOtherMuenchner
> 
> > I do not find the release notes anymore.
> 
> On some Samsung Galaxy models you can select
> Settings > Software update > Last update
> which may have a link to the Samsung site, such as:
> 
> https://doc.samsungmobile.com/SM-G800F/DBT/doc.html
> 
> That may be the right link for your device. If it is, it doesn't say very much except:
> "The security of your device has been improved."

After opening that link my risk status was also updated. Let's see if this will work throughout the next days.

**Comment by dsarkar** [comment]
Hi @AnOtherMuenchner, @sjnfr,

Thank you very much for the feedback, the developers are in informed about your experience. DS

---
Corona-Warn-App Open Source Team

**Comment by sjnfr** [comment]
After the update was provided in PlayStore and after updating my CWA, the risk calculation screen immediately updated, too. So, therefore, looks like the problem is solved. Thanks for the help!

**Comment by AnOtherMuenchner** [comment]
For information: Since the firmware update on thursday 2020-12-17, the CWA now does a status update every 24 hours and some minutes. In my case on 2020-12-17, 20:53 -> 2020-12-18, 21:00 -> 2020-12-19, 21:13. The CWA itself is still version 1.7.1.

**Comment by dsarkar** [comment]
@AnOtherMuenchner, thanks for the feedback, info is forwarded to the developer. DS

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
It sounds like the issue with Samsung Galaxy S5 mini is solved. Is there anybody still seeing a problem with the timestamp in the Corona-Warn-App not getting updated when using the latest version of the app (currently 1.10.1)?

**Comment by IT-Cons-Max** [comment]
The issue is solved on my Samsung Galaxy S5 neo (Android 6.0.1) since installation of CWA version 1.9.1 and **without** an OS-update.

**Comment by dsarkar** [comment]
@IT-Cons-Max Thanks for the feedback, very much appreciated. Info is forwarded to the developer. DS

---
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
Some users are still experiencing this problem, mostly Samsung devices. We are still looking into the issue.

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
Hello everyone,

We have got news about the progress on this issue. The root cause for this behaviour is that some Android vendors disable prioritized background updates automatically due to their battery optimization settings, **even if prioritized background updates were manually enabled for the app in the system settings**. There is nothing we can do in the CWA to prevent this. It has to be fixed by the vendor with a firmware update.

----
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Dear community, 

This issue has been inactive for a while. We will close it, feel free to re-open if necessary. Thanks for contributing here. Best wishes, DS 

---
Corona-Warn-App Open Source Team
