### ISSUE TITLE
Missing padding on My Check-Ins screen

### ISSUE THREAD

**Issue by fynngodau** [corona-warn-app/cwa-app-android#2849]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Describe the bug

Some padding is missing on the Check-In screen while the user is checked in to an event or a location between the duration box and the Check Out Now button.

| Device | My QR Codes (has correct padding) | My Check-Ins (has incorrect padding) |
|:--|---|---|
| 1 | ![Screenshot_1618576894](https://user-images.githubusercontent.com/16943720/115025607-dbe49700-9ec1-11eb-82ef-d884646bbb58.png) | ![Screenshot_1618576757](https://user-images.githubusercontent.com/16943720/115025628-e2730e80-9ec1-11eb-8db0-45c6aec634fa.png) |
| 2 | ![Screenshot_1618576286](https://user-images.githubusercontent.com/16943720/115025656-ebfc7680-9ec1-11eb-914f-89968740dfe9.png) | ![Screenshot_1618576275](https://user-images.githubusercontent.com/16943720/115025682-f3238480-9ec1-11eb-82b0-85782f18258d.png) |
2 with "Small" Font size | ![Screenshot_1618694223](https://user-images.githubusercontent.com/16943720/115126938-14c06100-9fd3-11eb-9feb-d448232e7c0b.png) | ![Screenshot_1618694213](https://user-images.githubusercontent.com/16943720/115126934-0a05cc00-9fd3-11eb-9b63-c7881b01946e.png)

As you can see from the screenshots, the exact amount of space that will be between the box and the Checkout button depends on the specific device's configuration, including dpi as well as font size.

## Steps to reproduce the issue

Play around with different device configurations on the emulator. Specifically, device "1" is the device profile "Galaxy Nexus" from the Android Emulator toolset, and "2" is the "Pixel 2" preconfiguration.

## Expected behavior

Padding should be the same on the My QR Codes screen as on the My Check-Ins screen.

---
Internal Tracking ID: [EXPOSUREAPP-6534](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6534)

**Comment by dsarkar** [comment]
@fynngodau Thanks. Internal Tracking ID: [EXPOSUREAPP-6534](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6534)

---
Corona-Warn-App Open Source Team

**Comment by fynngodau** [comment]
I added new screenshots from the same device with a smaller font size to illustrate that the button can also overlap the duration box on the card. Hence, I think this should be fixed before release.

**Comment by dsarkar** [comment]
@fynngodau thanks. added to ticket.

**Comment by d4rken** [comment]
I fixed this in https://github.com/corona-warn-app/cwa-app-android/pull/2826

I wasn't able to get it into 2.0.x though :frowning:

**Comment by harambasicluka** [comment]
Will be fixed with https://github.com/corona-warn-app/cwa-app-android/pull/2826 by @d4rken.

**Comment by fynngodau** [comment]
@d4rken Oh, awesome, thank for the hint. I cherry-picked the commit into CCTG. Closing this issue since it has already been resolved.

**Comment by MikeMcC399** [comment]
@dsarkar / @fynngodau 

Could we please re-open this issue since the corresponding fix has not been released yet?

Users keep reporting it and I think most people don't think of looking in the list of closed issues before opening a new issue.

**Comment by MikeMcC399** [comment]
I verified this fixed in the current release 2.1.2.

Pixel 3a, Android 11, CWA 2.1.2

1. Settings > Display > Advanced
2. Set Font size to Small
3. Open CWA
4. Scroll down to CREATE QR CODE and tap it
5. Tap NEXT if necessary
6. Tap + QR CODE
7. Tap Retail
8. Enter A in Description and B in Place, Tap SAVE
9. Tap CHECK IN
10. Tap ACCEPT if necessary
11. Tap CHECK IN
12. 

![image](https://user-images.githubusercontent.com/66998419/117143396-1353ae80-adb1-11eb-85f0-ec61b7649111.png)

The same steps carried out in CWA 2.0.3 result in the CHECK OUT NOW block overlapping the Duration block in the screen "My Check-Ins".

**Comment by MikeMcC399** [comment]
Whilst I was checking this fix, I noticed a new problem which I logged under https://github.com/corona-warn-app/cwa-app-android/issues/3086 "Duration display in Event overflows box with Largest font" which is on the same layout and with the Largest font size.

**Comment by fynngodau** [comment]
The padding is still not enough, compared to the My QR Codes view, like seen in the second set of screenshots in my original post.

**Comment by MikeMcC399** [comment]
@fynngodau 
> The padding is still not enough, compared to the My QR Codes view, like seen in the second set of screenshots in my original post.

I did wonder whether the padding is enough. At least there is no overlap.

So it seems the PR https://github.com/corona-warn-app/cwa-app-android/pull/2826 from @d4rken needs to be revisited for some more tweaking.

It would be good to have feedback about whether a new issue would be cleaner to handle, rather than keeping this one open.

**Comment by heinezen** [comment]
@MikeMcC399 @fynngodau 

The issue can stay open for now. The ticket has already been updated.

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@fynngodau 

The layout seems to be fixed now. I looked again using CWA 2.19.2

![image](https://user-images.githubusercontent.com/66998419/160229833-05ebc21d-08ad-4615-b3d2-cba59b2c0c82.png)

**Comment by MikeMcC399** [comment]
@fynngodau 
Perhaps you could take a look to decide if this issue is fixed and can be closed now?

**Comment by svengabr** [comment]
I have just checked the linked Jira issue.

Jira Ticket is flagged as:
Resolution: `Wont Fix`
Status: `Obsolete`

Developer comment:
> Depending on the font size, the padding is not enough. I will reopen the ticket.

> I think padding isn't the right fix, I would suggest a barrier.

> The issue does not seem to exist anymore. Set this ticket to completed.

**Comment by fynngodau** [comment]
Sorry for my inactivity here, @MikeMcC399, I did check a while ago and it seemed correct now but I forgot to close the issue accordingly. Thanks for closing, @svengabr.
