### ISSUE TITLE
Deadman notification is send too often

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-android#3625]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Xiaomi Mi A2
- Android version: 10
- App version: 2.4.3

## Describe the bug

The deadman notification is send, even if the last risk calculation isn't older than 36h. 

## Steps to reproduce the issue

Not really clear how to reproduce this issue.

## Expected behaviour

The deadman notification should only be send after 36h without a successful risk calculation.

## Additional context

1. This bug report is based on the information a user shared on Twitter: https://twitter.com/miwie/status/1411307803457867776?s=20
2. There is a bug report over at CCTG since 2 weeks, the user there reports that the issue was introduced with version 2.3 (https://codeberg.org/corona-contact-tracing-germany/cwa-android/issues/143)

----
Internal Tracking-ID: [EXPOSUREAPP-7955](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7955)

**Comment by MikeMcC399** [comment]
@Ein-Tim 
There is a PR in 2.5.x https://github.com/corona-warn-app/cwa-app-android/pull/3563 related to Deadman notifications. I don't know if it will fix the issue you report though.

**Comment by Ein-Tim** [comment]
Thanks @MikeMcC399! Let's see what the community managers will say and whether the PRs are supposed to fix this issue.

**Comment by thomasaugsten** [comment]
https://github.com/corona-warn-app/cwa-app-android/pull/3533 in v2.5 should improve the behavior. We plan a release in the next 14 days

**Comment by vaubaehn** [comment]
Without looking into the code, just reading the introductory texts of the PRs, it sounds like #3563 will revert #3533, unintentionally? #3533 wants to get away from the package date, but #3563 wants to use the package date?

**Comment by MikeMcC399** [comment]
@vaubaehn 
> After a short peek: it's partly reverted (l36 of the effected file)

I agree that the current https://github.com/corona-warn-app/cwa-app-android/blob/c87daaa408abdcb0296fbc1b1a4933918746b2bf/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/deadman/DeadmanNotificationTimeCalculation.kt#L36 has been reverted.

It seems the net result of the two PRs #3533 and #3563 is as follows:

```
$ git diff b92471 52e1 -- Corona-Warn-App/src/main/java/de/rki/coronawarnapp/deadman/DeadmanNotificationTimeCalculation.kt
diff --git a/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/deadman/DeadmanNotificationTimeCalculation.kt b/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/deadman/DeadmanNotificationTimeCalculation.kt
index 8e1787b8d..de21b1095 100644
--- a/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/deadman/DeadmanNotificationTimeCalculation.kt
+++ b/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/deadman/DeadmanNotificationTimeCalculation.kt
@@ -38,7 +38,7 @@ class DeadmanNotificationTimeCalculation @Inject constructor(

         Timber.d("Last successful diagnosis key package download: $lastSuccess")
         return if (lastSuccess != null) {
-            getHoursDiff(lastSuccess.createdAt).toLong()
+            getHoursDiff(lastSuccess.pkgDateTime.toInstant()).toLong()
         } else {
             (DEADMAN_NOTIFICATION_DELAY * DateTimeConstants.MINUTES_PER_HOUR).toLong()
         }

```

**Comment by vaubaehn** [comment]
@heinezen 
I think it would be better to remove the fix 2.5 label for now and to wait for clarification from devs. As you can read from above its unclear whether the intended enhancement was maybe reverted. Also, #3533 is targeting metered connections. For me it's also unclear whether all reports that could be found in Google Play Store reviews deal with unmetered connections or if also people using WiFi are affected.

Hope you have a nice Sunday!

**Comment by heinezen** [comment]
@vaubaehn 

The information is from the Jira ticket, so it already comes from the devs. I don't know if there will be more PRs, but the fix for this problem is planned for 2.5.

----
Corona-Warn-App Open Source Team

**Comment by chiljamgossow** [comment]
https://github.com/corona-warn-app/cwa-app-android/pull/3563 is not reverting the fix as the createdAt timestamp is still used to calculate the delay. It just takes it from the most recent package from the server. This makes only a difference for those who play with the device time and is intended to make it work properly again when the device time is correct.

**Comment by chiljamgossow** [comment]
> @vaubaehn
> 
> > After a short peek: it's partly reverted (l36 of the effected file)
> 
> I agree that the current
> 
> https://github.com/corona-warn-app/cwa-app-android/blob/c87daaa408abdcb0296fbc1b1a4933918746b2bf/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/deadman/DeadmanNotificationTimeCalculation.kt#L36
> 
> has been reverted.
> It seems the net result of the two PRs #3533 and #3563 is as follows:
> 
> ```diff
> $ git diff b92471 52e1 -- Corona-Warn-App/src/main/java/de/rki/coronawarnapp/deadman/DeadmanNotificationTimeCalculation.kt
> diff --git a/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/deadman/DeadmanNotificationTimeCalculation.kt b/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/deadman/DeadmanNotificationTimeCalculation.kt
> index 8e1787b8d..de21b1095 100644
> --- a/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/deadman/DeadmanNotificationTimeCalculation.kt
> +++ b/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/deadman/DeadmanNotificationTimeCalculation.kt
> @@ -38,7 +38,7 @@ class DeadmanNotificationTimeCalculation @Inject constructor(
> 
>          Timber.d("Last successful diagnosis key package download: $lastSuccess")
>          return if (lastSuccess != null) {
> -            getHoursDiff(lastSuccess.createdAt).toLong()
> +            getHoursDiff(lastSuccess.pkgDateTime.toInstant()).toLong()
>          } else {
>              (DEADMAN_NOTIFICATION_DELAY * DateTimeConstants.MINUTES_PER_HOUR).toLong()
>          }
> ```

The result is: 

suspend fun getDelay(): Long {
        val lastSuccess = keyCacheRepository.allCachedKeys()
            .first()
            .filter { it.info.isDownloadComplete }
            .maxByOrNull { it.info.pkgDateTime }
            ?.info

        Timber.d("Last successful diagnosis key package download: $lastSuccess")
        return if (lastSuccess != null) {
            getHoursDiff(lastSuccess.createdAt).toLong()
        } else {
            (DEADMAN_NOTIFICATION_DELAY * DateTimeConstants.MINUTES_PER_HOUR).toLong()
        }
    }

**Comment by vaubaehn** [comment]
Hi @chiljamgossow 

> #3563 is not reverting the fix as the createdAt timestamp is still used to calculate the delay. It just takes it from the most recent package from the server. This makes only a difference for those who play with the device time and is intended to make it work properly again when the device time is correct.

Thanks a lot for your clarification!
Let's hope the deadman will behave properly from now on!

**Comment by heinezen** [comment]
It should be fixed in the current release. Please report back if it was fixed for you or if you still experience the issue..

----
Corona-Warn-App Open Source Team

**Comment by vaubaehn** [comment]
I admit that following user report from Google Play Store reviews today is not too easy to understand, but I'm interpreting it in the way, that the issue is not fixed for all yet:

> Leider musste ich sie wieder, da die neuen Funktionen einfach nur nerven, dass ich die App jeden Tag aufrufen soll., wenn es was für melden gibt dann soll die app das natürlich melden dass ich einen risikostatus habe und nicht aktiv nachgucken musst ob ich ein risikostatus habe

But I found only one report since release of 2.5.1

**Comment by Ein-Tim** [comment]
@vaubaehn 

Thanks. The user I was in contact with via Twitter said that this has been fixed for him. 
So from my side, this can be closed, but probably it should be ensured that this really has been fixed before.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Since there are no clear steps to reproduce in the original report, it would be hard to verify with certainty if the issue is fixed.

Perhaps leave it open for one more week and then close it if there are no new reports?

**Comment by dsarkar** [comment]
@MikeMcC399 @vaubaehn @Ein-Tim FYI, internal ticket has been reopened, issue is being analysed again. We still get this issue reported in the PlayStore.

**Comment by MikeMcC399** [comment]
@dsarkar 
>  internal ticket has been reopened, issue is being analysed again. We still get this issue reported in the PlayStore.

Are there any known parameters where the issue occurs? Can we help in any way to narrow down the conditions?

**Comment by vaubaehn** [comment]
@d4rken @fynngodau 
What happens if the check for `isTracingEnabled` for the DeadManNotification results to `null`? Would the notification be displayed then?
@fynngodau 
I must confess that I don't have any idea what is the corresponding system level for CCTG what is ENF for CWA... You're either using ENF via Google Mobile Services _or_ MircoG, right? From the reporting users in https://codeberg.org/corona-contact-tracing-germany/cwa-android/issues/143, do we know what implementation they're using?

**Comment by fynngodau** [comment]
@vaubaehn

>  What happens if the check for `isTracingEnabled` for the DeadManNotification results to `null`? Would the notification be displayed then?

I don't think this should happen but looking at the code I'm inclined to say "no, the notification would not be displayed". I am not entirely certain though.

>what is the corresponding system level for CCTG what is ENF for CWA... You're either using ENF via Google Mobile Services or MircoG, right?

Right, see https://codeberg.org/corona-contact-tracing-germany/cwa-android/#about:

> If microG is already installed on your system, it will make use of its Exposure Notifications implementation. Otherwise, it will use the bundled implementation. It will never connect to the Google Play services Exposure Notification System. You can find out which implementation is used by checking the status at the bottom of the App Information screen.

Thus, the users in our issue which you linked are using either bundled or external microG, but surely not Google's Exposure Notifications implementation. Thus no special "system level" code is required (furthermore, I would not count GMS as "system level").

**Comment by d4rken** [comment]
> @d4rken @fynngodau
> What happens if the check for `isTracingEnabled` for the DeadManNotification results to `null`? Would the notification be displayed then?

You mean here?

https://github.com/corona-warn-app/cwa-app-android/blob/63df24be9d2bc1bfb324325d79b1c8b0f8606f4d/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/deadman/DeadmanNotificationScheduler.kt#L32-L44

it can't be null (compiler says no):
https://github.com/corona-warn-app/cwa-app-android/blob/63df24be9d2bc1bfb324325d79b1c8b0f8606f4d/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/modules/tracing/TracingStatus.kt#L11-L12

It either emits nothing (then nothing will be scheduled or canceled, or a true/false, or it throws (then the app crashes).

**Comment by Ein-Tim** [comment]
Any update available here @dsarkar?

**Comment by Ein-Tim** [comment]
Okay, thanks @dsarkar!

Closing this issue.
