### ISSUE TITLE
Wrong federal state for some cities on 7 days incidence cards, affects "Thuringia" / "Thüringen" only

### ISSUE THREAD

**Issue by bedo2991** [corona-warn-app/cwa-app-android#4327]
## Technical details

- Device name: Pixel 4a
- Android version: 12
- App version: 2.13.1

## Describe the bug

Kreis: Erfurt
is in Thüringen, but the card shows the hospitalization value from Baden-Württemberg

## Steps to reproduce the issue
Add a local 7-day incidence for "Thüringen" > Erfurt (maybe even any city, also tried Ilm-Kreis and it's also wrong.

![Screenshot_20211104-101737](https://user-images.githubusercontent.com/3187778/140288442-61e3cf44-922b-47f8-8969-f0384d0a4097.png)

## Expected behaviour
Should show values from the right region

## Additional context

I don't have an Iphone, so I don't really know if this problem also affects the iOS version.

---
Internal Tracking ID: [EXPOSUREAPP-10406](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10406)

**Comment by dsarkar** [comment]
Dear @bedo2991 @Ein-Tim @MikeMcC399 Thanks for reporting this issue. Internal Tracking ID: [EXPOSUREAPP-10406](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10406)

Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@bedo2991 @MikeMcC399 It always shows "Baden-Württemberg", whatever "Kreis" you choose?

**Comment by bedo2991** [comment]
@dsarkar no, for Kassel I get Hessen, Nürnberg I get Bayern...

**Comment by MikeMcC399** [comment]
Maybe because "Thüringen" is the last state in the list and it wraps around to the first one, which is "Baden-Württemberg"?

All other states seem to work OK.  (I tried several, but not all.)

**Comment by MikeMcC399** [comment]
The bug is in 
https://github.com/corona-warn-app/cwa-app-android/blob/d137410cfb1d8aff3e174563590f775110ee0afa/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/LocalIncidenceAndHospitalizationCard.kt#L118

It should be using the string `analytics_userinput_federalstate_th` for "Thuringia", not `analytics_userinput_federalstate_bw` for "Baden-Württemberg".

https://github.com/corona-warn-app/cwa-app-android/blob/d137410cfb1d8aff3e174563590f775110ee0afa/Corona-Warn-App/src/main/res/values/strings.xml#L1903-L1904

It only affects "Thuringia" / "Thüringen" so it would be good to change the title of this issue. Other states are not affected.

**Comment by mlenkeit** [comment]
@MikeMcC399 thank you for identifying the root cause of this 👍 We plan to include the fix in one of the next (patch) releases.

@all: note that the figure itself is the correct one for Thüringen.

**Comment by dsarkar** [comment]
Fix planned: Hotfix 2.13.3 [Android] / Hotfix 2.13.2 [iOS]

**Comment by Ein-Tim** [comment]
FYI: PR: https://github.com/corona-warn-app/cwa-app-android/pull/4345

**Comment by MikeMcC399** [comment]
This issue is logged as fixed in the pre-release version [v2.13.3-RC0](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.13.3-RC0)
PR https://github.com/corona-warn-app/cwa-app-android/pull/4345 "Fix relation between administrative units belonging to federal state Thuringia (EXPOSUREAPP-10406)".

I checked the current [release/2.13.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.13.x) branch.

The statistics tile for Erfurt now correctly shows "Thüringen". See the marked up screenshot below:

![image](https://user-images.githubusercontent.com/66998419/141447165-d27cc79b-6ab1-4637-8e16-4058d350308e.png)

**Comment by MikeMcC399** [comment]
@bedo2991 
I'm seeing this fixed in the latest release from today (2.13.3). Would you like to check with this version? I'm already seeing it in the Google Play Store so I guess you should be able to get it as well.

**Comment by bedo2991** [comment]
I don't see any update available for me on the play store. I still have the 2.13.2

**Comment by MikeMcC399** [comment]
@bedo2991 
> I don't see any update available for me on the play store. I still have the 2.13.2

I'm just checking with the Open Source Team about the rollout. (See https://github.com/corona-warn-app/cwa-website/issues/2090.) 

I'm definitely seeing 2.13.3 on https://play.google.com/store/apps/details?id=de.rki.coronawarnapp but the way that Google handles rollouts means that different users can receive updates at different times.

**Comment by bedo2991** [comment]
Got it now, looks fixed to me.

**Comment by dsarkar** [comment]
Dear @bedo2991 and community. Thanks for reporting and the feedback. Best, DS 

---
Corona-Warn-App Open Source Team
