### ISSUE TITLE
App crashes upon startup

### ISSUE THREAD

**Issue by bedo2991** [corona-warn-app/cwa-app-android#4331]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Pixel 4a
- Android version: 12
- App version: 2.13.1

## Describe the bug

Can't open the app anymore.

## Steps to reproduce the issue
After rebooting the phone at around 12:15, I am not able to start the corona warn app anymore.
I tried to clear the app cache, no difference.
I tried to open the app with the Bluetooth disabled and the Bluetooth enabled, no difference.

I sent the logs 2 times through the Android feedback.

## Expected behaviour
The app should open

## Additional context
May be related to a server-side fix for #4327 ?

---
Internal Tracking ID: [EXPOSUREAPP-10154](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10154)

**Comment by Ein-Tim** [comment]
There is a user on Twitter who also says that the app crashes on startup: https://twitter.com/der_gute_freund/status/1456151117600018438?s=21

**Comment by Ein-Tim** [comment]
@bedo2991 

Did you maybe update to 2.13.1 and since then the app won't open?

**Comment by bedo2991** [comment]
@Ein-Tim no, I reported another bug this morning running the 2.13.1 and it was working at that time.

**Comment by Ein-Tim** [comment]
@bedo2991 

Ah yeah, sorry 😅

**Comment by magilus** [comment]
Same issue for me as of today on Moto x4. I have also sent crash reports. I have two different kind of certificates stored in my app, Pfizer and J&J. This is a massive issue as it prevents me from showing my COVID pass. Version 2.13.1. this must be prioritized IMO and a workaround has to be published.

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Any update you could give us here?

**Comment by dsarkar** [comment]
@bedo2991 @Ein-Tim Devs are looking into this.

**Comment by Ein-Tim** [comment]
2.13.1 Rollout has been stopped: https://twitter.com/coronawarnapp/status/1456317293886062592?s=21

**Comment by thomasaugsten** [comment]
@bedo2991  @magilus 
Please contact me directly to test an fix for your issue
thomas.augsten@sap.com

**Comment by morckx** [comment]
Probably same crash on startup here since yesterday with v2.13.1 which worked before:

```
--------- beginning of main
11-05 19:49:42.487 14323 14350 I i.coronawarnap: Clamp target GC heap from 339MB to 256MB
11-05 19:49:42.487 14323 14350 I i.coronawarnap: Alloc concurrent copying GC freed 26(16KB) AllocSpace objects, 0(0B) LOS objects, 4% free, 243MB/256MB, paused 58us total 933.460ms
11-05 19:49:42.487 14323 14350 W i.coronawarnap: Throwing OutOfMemoryError "Failed to allocate a 30545264 byte allocation with 13118016 free bytes and 12MB until OOM, target footprint 268435456, growth limit 268435456" (VmSize 14224352 kB)
--------- beginning of crash
11-05 19:49:42.489 14323 14350 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
11-05 19:49:42.489 14323 14350 E AndroidRuntime: Process: de.rki.coronawarnapp, PID: 14323
11-05 19:49:42.489 14323 14350 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 30545264 byte allocation with 13118016 free bytes and 12MB until OOM, target footprint 268435456, growth limit 268435456
11-05 19:49:42.489 14323 14350 E AndroidRuntime:        at java.util.Arrays.copyOfRange(Arrays.java:3589)
11-05 19:49:42.489 14323 14350 E AndroidRuntime:        at java.lang.StringBuffer.toString(StringBuffer.java:669)
11-05 19:49:42.489 14323 14350 E AndroidRuntime:        at java.io.StringWriter.toString(StringWriter.java:210)
11-05 19:49:42.489 14323 14350 E AndroidRuntime:        at com.google.gson.JsonElement.toString(JsonElement.java:5)
11-05 19:49:42.489 14323 14350 E AndroidRuntime:        at de.rki.coronawarnapp.util.serialization.adapter.JsonNodeAdapter.read(JsonNodeAdapter.kt:6)
11-05 19:49:42.489 14323 14350 E AndroidRuntime:        at de.rki.coronawarnapp.covidcertificate.vaccination.core.repository.storage.ContainerPostProcessor$create$1.read(ContainerPostProcessor.kt:1)
11-05 19:49:42.489 14323 14350 E AndroidRuntime:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:1)
11-05 19:49:42.489 14323 14350 E AndroidRuntime:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:9)
11-05 19:49:42.489 14323 14350 E AndroidRuntime:        at de.rki.coronawarnapp.covidcertificate.vaccination.core.repository.storage.ContainerPostProcessor$create$1.read(ContainerPostProcessor.kt:1)
11-05 19:49:42.489 14323 14350 E AndroidRuntime:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:1)
11-05 19:49:42.489 14323 14350 E AndroidRuntime:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:9)
11-05 19:49:42.489 14323 14350 E AndroidRuntime:        at de.rki.coronawarnapp.covidcertificate.vaccination.core.repository.storage.ContainerPostProcessor$create$1.read(ContainerPostProcessor.kt:1)
11-05 19:49:42.489 14323 14350 E AndroidRuntime:        at com.google.gson.Gson.fromJson(Gson.java:6)
11-05 19:49:42.489 14323 14350 E AndroidRuntime:        at com.google.gson.Gson.fromJson(Gson.java:20)
11-05 19:49:42.489 14323 14350 E AndroidRuntime:        at com.google.gson.Gson.fromJson(Gson.java:37)
11-05 19:49:42.489 14323 14350 E AndroidRuntime:        at de.rki.coronawarnapp.covidcertificate.vaccination.core.repository.storage.VaccinationStorage.load(VaccinationStorage.kt:16)
11-05 19:49:42.489 14323 14350 E AndroidRuntime:        at de.rki.coronawarnapp.covidcertificate.vaccination.core.repository.VaccinationRepository$internalData$1.invokeSuspend(VaccinationRepository.kt:6)
11-05 19:49:42.489 14323 14350 E AndroidRuntime:        at de.rki.coronawarnapp.covidcertificate.vaccination.core.repository.VaccinationRepository$internalData$1.invoke(VaccinationRepository.kt:2)
11-05 19:49:42.489 14323 14350 E AndroidRuntime:        at de.rki.coronawarnapp.util.flow.HotDataFlow$internalProducer$1.invokeSuspend(HotDataFlow.kt:11)
11-05 19:49:42.489 14323 14350 E AndroidRuntime:        at de.rki.coronawarnapp.util.flow.HotDataFlow$internalProducer$1.invoke(HotDataFlow.kt:2)
11-05 19:49:42.489 14323 14350 E AndroidRuntime:        at kotlinx.coroutines.flow.ChannelFlowBuilder.collectTo(Builders.kt:1)
11-05 19:49:42.489 14323 14350 E AndroidRuntime:        at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:1)
11-05 19:49:42.489 14323 14350 E AndroidRuntime:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
11-05 19:49:42.489 14323 14350 E AndroidRuntime:        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
11-05 19:49:42.489 14323 14350 E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
11-05 19:49:42.489 14323 14350 E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
```

**Comment by vaubaehn** [comment]
@morckx 
Your crash reports indicates that CWA tried to allocate ~30MB but failed because there were only ~13MB free...
Does your mobile usually run with that low memory, or is this the effect of the underlying bug (eating too much memory as a side effect)?

**Comment by morckx** [comment]
> @morckx Your crash report indicates that CWA tried to allocate ~30MB but failed because there were only ~13MB free... Does your mobile usually run with that low memory, or is this the effect of the underlying bug (eating too much memory as a side effect)?

IMHO this is not related to the the available RAM of my mobile (LMI with 6GB RAM on LineageOS 18.1),
also because the issue is 100% reproducible every time and otherwise I can't remember that I've seen this error message before. 

I think it's rather a memory management issue with the corona app – and/or an issue with the heap size of **12MB reserved for the app**. 

Googeling the error message suggests fixing the heap handling or increasing  heap size by setting:

```
<application>
        android:largeHeap="true"
</application>
```

**Comment by thomasaugsten** [comment]
Fix was created yesterday and is at the moment in review in the Google Playstore. 
We estimated a release in the next hours.

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Version 2.13.2 has been released on GitHub: https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.13.2
Is this version in rollout now?

**Comment by thomasaugsten** [comment]
Yes 30%

**Comment by thomasaugsten** [comment]
100% rollout

**Comment by MikeMcC399** [comment]
@bedo2991 
Could you give feedback please about if the crash is now resolved with either 2.13.2 containing the fix or the currently latest Android version 2.13.3?

**Comment by bedo2991** [comment]
It works for me on 2.13.2, I don't see any update available on the play store at the moment.

**Comment by jo-soft** [comment]
I'm running 2.14.1 on a Doodgee S88 with android 10 and still see the/a similar issue. After reboot I can start the app once but at some point it hangs forever during startup  even if I force stop it. 
I never had 2.13.x installed so ican't tell big it was working. 
Worked fine with an older version released this summer

**Comment by Ein-Tim** [comment]
@jo-soft 

I suggest you [open a new issue](https://github.com/corona-warn-app/cwa-app-android/issues/new/choose) for this problem. The developers will then take a look.

Thanks for reporting!

**Comment by jo-soft** [comment]
After I updated CarrierService to Version 86.0.410011749-carrierservices_20211115_02_RC00 it's working again. I cant say if it's related and idk the version installed before because it got auto updated
