### ISSUE TITLE
Cause 2: NotEnoughSpaceOnDiskException even though plenty free space

### ISSUE THREAD

**Issue by fabianhick** [corona-warn-app/cwa-app-android#732]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Describe the bug

Upon opening the app I'm confronted with Cause 2 even though there is enough storage available.
## Expected behaviour
No error message at all.

## Steps to reproduce the issue
1. Open the app
2. You are shown the following error upon pressing "Details":
![20200624_033348](https://user-images.githubusercontent.com/16404121/85486785-a043ae00-b5cb-11ea-8a59-5880d13d05de.jpg)
(sometimes multiple times)

## Technical details

- Mobile device: Samsung Galaxy Note 9
- Android version: 10

## Possible Fix
Maybe storage space availabiltity is not checked regulary?

## Additional context
Since installing the app I almost ran out of storage once.

It might be helpful to enable copying the stack trace.

----
Internal Tracking Id: EXPOSUREAPP-1852

**Comment by jakobmoellersap** [comment]
Thanks for your input! How much storage space is actually consumed? The current space threshold is set kind of high so this could happen if you go below the threshold

**Comment by fabianhick** [comment]
I still have ca. 600 MB of storage left.

**Comment by AlexanderAlferov** [comment]
@fabianhick for security we could not store information on SD/External card. Could you confirm that there is free space on internal memory? Thank you.

**Comment by fabianhick** [comment]
@AlexanderAlferov Sure! I currently only use internal storage. 
Usage: 127.4/128 GB
Free memory: 594 MB

**Comment by tkowark** [comment]
+1 for this issue. Samsung Galaxy A3, 553MB/15,5GB free

**Comment by sandrasie** [comment]
Same for me on a Samsung A3 2017. Even with >600Mb free memory (according to the system tools) it did not work. With now slightly above 700, it works again. 
The critical thing about this is, that one only notices this issue when opening the app. My app has not been downloading keys for 5 days when I did so.

**Comment by kilian-gebhardt** [comment]
I also have this issue on a Samsung Galaxy A3 2017 with about 500MB free internal memory.

**Comment by drillabit** [comment]
Me too! Samsung A3 2017 fails with 400 to 500MB of internal Storage, works with 1GB ( after deleting data of other apps). As it takes less than a second to update the status once it works, it is unlikely that there are 400MB of data downloaded!

**Comment by jakobmoellersap** [comment]
Thanks for reporting guys. Our current assumption is that there is not enough space broadcast as available from the OS and we are looking into it.

**Comment by ArneLimburg** [comment]
I had this problem, too (on an A5). Even when there is actually not enough space, the error message should be improved. The consequence of the problem (not syncing with the server I guess, so not checking for infections?) should be clearly stated in the message.
And maybe a link to the OS to clear memory should be provided?

**Comment by yorickreum** [comment]
I am not convinced that this is a threshold problem. I guess the error is thrown falsely without passing the threshold. I encountered it on my BlackBerry with at least 500 MB free (so more than the 200 MB threshold that is currently set). It also seems to occur on iOS, even with more than 200 GB (!) free. Please see: https://twitter.com/henningtillmann/status/1276998571959689216

**Comment by yorickreum** [comment]
I also agree with @ArneLimburg, since this error will appear commonly anyway, the app should show a userfriendly error message.

**Comment by tkowark** [comment]
@yorickreum Yes, the issue also occurs on iOS, but that's a different topic, as the error there is thrown by the (Apple) Exposure Notification Framework itself, and not the app.

**Comment by yorickreum** [comment]
@tkowark Okay! I will wait for the update and see if this fixes the problem on my BlackBerry.

**Comment by Kroko7733** [comment]
Had the same problem on my Huawei p10 with ~710 MB internal storage free for the last 3 days (pictures attached).
Deleted some things (not because of that) and suddenly app worked again with no error. Tried to recreate it with going down with free storage but didn't work.
I did not update the App, so should be still a bug to fix.
![Screenshot_20200629-153127](https://user-images.githubusercontent.com/39100259/86017011-d34ecd00-ba23-11ea-80bd-0050ed72b25d.jpg)
![WIN_20200629_15_30_34_Pro](https://user-images.githubusercontent.com/39100259/86016378-004eb000-ba23-11ea-876e-2901186a2625.jpg)
![WIN_20200629_15_31_03_Pro](https://user-images.githubusercontent.com/39100259/86016387-017fdd00-ba23-11ea-9bb2-7b12bce37b57.jpg)
![WIN_20200629_15_31_13_Pro](https://user-images.githubusercontent.com/39100259/86016395-02b10a00-ba23-11ea-87a0-c9b176000723.jpg)

**Comment by jakobmoellersap** [comment]
The update was not deployed yet.

**Comment by grpingel** [comment]
> Same for me on a Samsung A3 2017. Even with >600Mb free memory (according to the system tools) it did not work. With now slightly above 700, it works again.
> The critical thing about this is, that one only notices this issue when opening the app. My app has not been downloading keys for 5 days when I did so.

I think the fact that there is no automatic notification about the memory problem should also be changed.

**Comment by Ced4** [comment]
Had the same issue the last days. Glad to see that there is already a potential fix available. Additionally I agree to @grpingel that there should be a notification to make the user aware that the app is not working properly due to low disk space.

I would assume that even with the fix this error might occur with having 500MB or less left. Maybe the error message could be improved by explaining to the user why this is not enough as the first reaction might always be something like "I have 400MB space left, what the hell is the App doing?"

**Comment by jakobmoellersap** [comment]
Good point, we are thinking of improving the error message to explain this implementation detail.

**Comment by ennyKey** [comment]
Any update on this problem?
The App is now not working since more than 11 days on my device.
Due to FAQ it need 20MB, I have more than 600MB free space on internal storage.
Hopefully this bug will be fixed soon. Because without the risk detection this App makes absolutely no sense.

**Comment by feyyd1** [comment]
Same here. App is not updating for weeks. 500MB free space and still getting the error message.

**Comment by schulzch** [comment]
Ran into the same problem (Google Pixel). I think the App should displays some numbers in the error message:
1. how much space is required (`FREE_SPACE_THRESHOLD`)
2. how much space it thinks is available.

**Comment by tkowark** [comment]
Thanks for the suggestion @schulzch . We'll take this to the product managers and push for this to be implemented. As the free space seems to be wrongly reported by some OS, this would at least make clear which amount of free space to aim for.

Following suggestions for an error message:
"There is not enough space left on the device. The operating system reports that XXXMB are free and YYMB are needed for the App to perform risk calculation."

And this message should pop up as soon as the crash is detected, not only when opening the app.

Any additions / objections?

**Comment by ArneLimburg** [comment]
@tkowark As I wrote earlier: The message should clearly state that the app stops working correctly, too

**Comment by daimpi** [comment]
Is this issue fixed with the release of [1.1.1](https://github.com/corona-warn-app/cwa-app-android/releases/tag/1.1.1) (which contains https://github.com/corona-warn-app/cwa-app-android/pull/760)?

**Comment by schulzch** [comment]
> Is this issue fixed with the release of [1.1.1](https://github.com/corona-warn-app/cwa-app-android/releases/tag/1.1.1) (which contains #760)?

Lowering the threshold is only a mitigation - the error message is still pretty much useless.

**Comment by deepdigger** [comment]
I'm still seeing this error message at v.1.3.0, Samsung a5 2016 at intern 15.4/16GB and extern 31.9/32GB memory consumption.
When more memory is free it works, but I still wish for a more consumer-usable error message

**Comment by dl1chb** [comment]
I have the same issue. I cannot wait, until it is fixed. So question: can I move everything to a new phone? Because if that is possible, I simply bye a second one...

**Comment by daimpi** [comment]
@dl1chb unfortunately you cannot migrate the keys from your old phone to your new one unless you have root, for more info see [here](https://github.com/corona-warn-app/cwa-wishlist/issues/8#issuecomment-712460713).

**Comment by dsarkar** [comment]
Dear @fabianhick, @dl1chb, @deepdigger, @feyyd1, @Ced4, @ArneLimburg, @sandrasie, @kilian-gebhardt, @drillabit, @Kroko7733, @yorickreum, and community:

We would appreciate some feedback: Do you still experience this issue with the actual CWA version 1.6.1? Thanks!

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by dl1chb** [comment]
@dsarkar I managed to free up enough space and actually got a new smartphone. But I can update to 1.6.1 on my old and try to reproduce this if it helps you

**Comment by MikeMcC399** [comment]
Since [CWA Android 1.7.1](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.7.1) is just being released, I would hang on for a little bit. I can't see it on the Google Play Store right now, but it should be out soon.

**Comment by dsarkar** [comment]
Dear @fabianhick, @dl1chb, @deepdigger, @feyyd1, @Ced4, @ArneLimburg, @sandrasie, @kilian-gebhardt, @drillabit, @Kroko7733, @yorickreum, and community:

We would appreciate some feedback: Do you still experience this issue with the actual CWA version 1.7.1? Thanks!

Best wishes,
DS

Corona-Warn-App Open Source Team

**Comment by yorickreum** [comment]
I did not experience this issue in the last weeks.

**Comment by ennyKey** [comment]
I tested it with 110 MB free storage and the app worked.
So it seems to work.

**Comment by heinezen** [comment]
Should be fixed since CWA 1.5 since there have been no more reports about this issue.

----
Corona-Warn-App Open Source Team
