### ISSUE TITLE
"Risiko-Ermittlung dauerhaft aktiv" despite BlueTooth being disabled

### ISSUE THREAD

**Issue by icrf2000** [corona-warn-app/cwa-app-android#920]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Describe the bug

The green risk status box shows "Risiko-Ermittlung dauerhaft aktiv" despite the fact that I disabled BlueTooth a bit more than one day ago. The app correctly recognized that BlueTooth is disabled (shows "BLUETOOTH DEAKTIVIERT" and a red strike-through BlueTooth icon at the top of the screen). 

Side note: I reported something similar in #840. Back then, the app incorrectly showed "14 von 14 Tagen aktiv". In the meantime, you seem to have changed the text, no longer give the (anyway incorrect) number of active days. But in essence, the information shown to the user is still wrong. Personally I think it would be better to completely remove this information from the screen. Better no info than wrong/misleading/confusing/frustrating info. I know from private conversations with less technically affine people that they ARE confused and in the worst case, they might decide to deinstall the app:-( Don't get me wrong, I really appreciate what you achieved and I am happy with the app. That's the very reason why I beg to make it less confusing for other people who might not ask "why" and give the app a second chance.

In #840, I was told the behavior couldn't be improved due to limitations of the Google API. Plus that Android apps were unable to detect the fact that BlueTooth is disabled. At least the latter doesn't seem to be true (anymore), as written above, the app correctly tells me "BLUETOOTH DEAKTIVIERT", so it correctly detected this situation. 

## Expected behaviour

If BlueTooth is disabled (at least if disabled for an extended period of time), the app shouldn't say "Risiko-Ermittlung dauerhaft aktiv", rather give some warning or alike.

## Steps to reproduce the issue

1. Disable BlueTooth, leave it disabled for a while (> 1 day to be sure)
2. Look at the app's main screen, here the green risk status box

## Technical details

- Mobile device: Galaxy S10
- Android version: 10
- Google COVID-19 API: 15202902003
- App version 1.1.1

## Additional context

---
Related https://github.com/corona-warn-app/cwa-wishlist/issues/195

Related:
Internal Tracking ID: [EXPOSUREAPP-2518](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-2518)
Internal Tracking ID: [EXPOSUREAPP-3387](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3387)
Internal Tracking ID: [EXPOSUREAPP-4467](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4467)
Internal Tracking ID: [EXPOSUREAPP-5170](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5170)
https://github.com/corona-warn-app/cwa-app-android/issues/929

---
Internal Tracking ID: EXPOSUREAPP-1925
Internal Tracking ID: [EXPOSUREAPP-4467](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4467)

**Comment by SebastianWolf-SAP** [comment]
Thanks for the report. We'll have a look at that and discuss that with the dev team.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by Mtagxx** [comment]
If one switches off "COVID-19-Benachrichtigungen" for some days the message "Risiko-Ermittlung dauerhaft aktiv" will be displayed, too  if one turns on COVID-19-Benachrichtigungen and opens CWA. This is an error. A message like "Risiko-Ermittlung war für 13 der letzten 14 Tage aktiv" or something like this should be shown instead.

Best regards
Chris

**Comment by Mtagxx** [comment]
The problem still exists with CWA Version 1.3.0 and Google Play Services 20.30.19.
When will it be fixed?

Best regards
Chris

**Comment by rsch136** [comment]
I am also experiencing this issue. The app claims "exposure logging permanently active" even though I had Bluetooth disabled for 3 days.

**Comment by daimpi** [comment]
There are lots of issues which concern this display of "active days", imho it would make sense to just drop it and be done with it (other ENF apps also don't have this): https://github.com/corona-warn-app/cwa-wishlist/issues/102 
Feel free to upvote 🙂.

**Comment by Mtagxx** [comment]
If either Bluetooth or "Standortdienste" or "COVID-19-Benachrichtigungen" is switched off for a whole day no TEK (Temporary Exposure Key, täglicher Diagnoseschlüssel) will be generated for that day. However the message "Risiko-Ermittlung dauerhaft aktiv" will be displayed anyway. Even if one switches off Bluetooth for three weeks this message will be displayed. That is wrong! What would happen if one would get tested COVID-19 positive? For those days with Bluetooth off no TEK will be available to upload. Or will the app tell one that 13 TEKs have been uploaded successfully anyway? In my opinion the number of "active days" should be equal to the number of available TEKs.

It will be helpful to see the correct number of active days in order to see if the app is still working correctly. Just remember the problems with "Aktualisierung". If you don't even have some indications how can you tell if it is still working?

**Comment by Mtagxx** [comment]
Hallo @daimpi,

no: TEKs are only generated if BT is on (and "Standort" and "COVID-19-Benachrichtigung" (sorry, I don't know the english words for that))! 

Please note that you don't have to access the TEK to find out if new ones are generated.
A message is written to the systemlog when a new one is generated. So for example one could parse the logfile to find it out ... :-)
I'm sure there is a more elegant method than that - just ask Google. 

An interested and curious user of the CWA will be eager to see if the app is still working correctly. If she never gets any new informations, sees some counters raising etc. she will quit opening the app daily. Why should one look at it anymore?
Therefore it is important that there are some indicators which are updated correctly.

But it is really bad if there are some numbers like "active days" which are obviously wrong like in the case with BT off for days. Users will totally loose confidence that the app is working correctly if even such an elementary thing is not handled adequately.

**Comment by daimpi** [comment]
@Mtagxx 
> no: TEKs are only generated if BT is on (and "Standort" and "COVID-19-Benachrichtigung" (sorry, I don't know the english words for that))!

That's interesting to know 🙂. But even in this case you'll get a TEK if BT was only enabled for a brief moment that day which would mean that you didn't really broadcast any useful rolling proximity identifiers (RPIs) even though you generated a TEK.

> So for example one could parse the logfile to find it out ... :-)

Does CWA have permissions to parse this logfile? 

> I'm sure there is a more elegant method than that - just ask Google.

Googles API is documented here: https://developers.google.com/android/exposure-notifications/exposure-notifications-api. Tbh I'm not aware of a call which would provide this functionality.

> An interested and curious user of the CWA will be eager to see if the app is still working correctly. If she never gets any new informations, sees some counters raising etc. she will quit opening the app daily. Why should one look at it anymore?
Therefore it is important that there are some indicators which are updated correctly.

I agree that the app should be made more engaging but I'd prefer this to come in form of enhanced functionality e.g. 
- [Venue registration](https://github.com/corona-warn-app/cwa-wishlist/issues/138)
- [More information on number of keys shared etc.](https://github.com/corona-warn-app/cwa-wishlist/issues/236)
- [Information on local regulations and restrictions](https://github.com/corona-warn-app/cwa-wishlist/issues/151)

> But it is really bad if there are some numbers like "active days" which are obviously wrong like in the case with BT off for days

As stated above: I personally don't think that presence of TEKs is a reliable indicator of "days active" and given that "days active" causes all kinds of trouble I've come around on the idea to [have it removed](https://github.com/corona-warn-app/cwa-wishlist/issues/102) for good.

Maybe it would be good to have the info on number of stored TEKs (if it can actually be assessed by CWA) shown in some menu within CWA for debugging purposes though or alternatively Google could maybe be asked to expose this info in their ENF settings menu 🙂.

**Comment by heinezen** [comment]
Fixed in CWA version 1.5. Since there haven't been new reports in two months, I'll close this issue.

----
Corona-Warn-App Open Source Team

**Comment by Mtagxx** [comment]
That's really funny: I'm using CWA version 1.6.0. I have switched off bluetooth for a couple of days and still get: "Risiko-Ermittlung dauerhaft aktiv". What is the meaning of the phrase "Risiko-Ermittlung dauerhaft aktiv"? Maybe I just understand it wrong?
![sc20201126](https://user-images.githubusercontent.com/68113972/100340871-1bc2e480-2fdc-11eb-91a8-65cf2dfe939e.jpg)

**Comment by heinezen** [comment]
Reopened due to user feedback. We will investigate the issue again.

----
https://github.com/corona-warn-app/cwa-app-android/issues/920

**Comment by icrf2000** [comment]
I have 1.7.1 in the meantime. The issue still exists. Here how it looks after having Bluetooth disabled for a bit more than 24 hours. It says "BLUETOOTH DEAKTIVIERT", shows the red alert in the notification bar, but nevertheless, pretends "Risiko-Ermittlung dauerhaft aktiv":

![Screenshot_20201129-084714_Corona-Warn](https://user-images.githubusercontent.com/11777822/100588776-8b91e180-32f2-11eb-851d-09bbd6facf02.jpg)

**Comment by dsarkar** [comment]
Dear @icrf2000,

Thanks for reporting. Please let us know 
- Android version
- Phone model:

Thanks.


Dear community, 

- can you reproduce this issue on your Android phone. Feedback very much appreciated.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by Mtagxx** [comment]
I'm using CWA version 1.7.1 in the meantime, too and the problem still exists. 
My Android version is 9, COVID-19-Benachrichtigungen Version 18204217000.
Phone model is Samsung Galaxy J3.

Please let me know, if additional informations are required.

Regards
Chris

**Comment by icrf2000** [comment]
phone: Samsung Galaxy S10
os: Android 10

Am 30. November 2020 10:08:37 MEZ schrieb dsarkar <notifications@github.com>:
>Dear @icrf2000,
>
>Thanks for reporting. Please let us know 
>- Android version
>- Phone model:
>
>Thanks.
>
>
>Dear community, 
>
>- can you reproduce this issue on your Android phone. Feedback very
>much appreciated.
>
>Best wishes,
>DS
>
>---
>Corona-Warn-App Open Source Team
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/corona-warn-app/cwa-app-android/issues/920#issuecomment-735655990

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by dsarkar** [comment]
@icrf2000, @Mtagxx, thanks for the feedback, could you upload screenshots showing this. I the meantime we will forward this information to the developers. Many thanks! Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by icrf2000** [comment]
What Screenshots would help you from me? Apart from the one I sent already I mean.

**Comment by dsarkar** [comment]
@icrf2000, the one you sent is good enough so far. Thanks. Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@icrf2000, @Mtagxx,

Thanks again for contributing here. Do you still have this issue with CWA version 1.9.1? Thanks. DS

---
Corona-Warn-App Open Source Team

**Comment by icrf2000** [comment]
hi! i just disabled bluetooth and will check tomorrow morning.

**Comment by Mtagxx** [comment]
Hello,
I'm using now cwa 1.9.1 (on Android 9), too. Still looks the same. However, if one switches off "COVID-19-Benachrichtigungen" then the view has changed: with version 1.7.1 something like "Bisher keine Risiko-Begegnungen   Risiko-Ermittlung war für 9 der letzten 14 Tage aktiv" is displayed but not with 1.9.1.
(Actually I got one "Risiko-Begegnung" with low risk, which is not shown anymore with version 1.7.1 and version 1.9.1 like in   previous versions:
  12-20 17:58:18.048  I ExposureNotificationJni: Matching done, total 433791 keys, find 1 keys match
  12-21 16:14:03.157  I ExposureNotificationJni: Matching done, total 450759 keys, find 1 keys match
  12-21 21:32:55.531  I ExposureNotificationJni: Matching done, total 450759 keys, find 1 keys match
)

Best regards
Chris

Version 1.7.1:
![sc_20201219-233032](https://user-images.githubusercontent.com/68113972/102891068-e6d07300-445d-11eb-8aff-e2920754ea7f.jpg)

Version 1.9.1:
![sc_20201222-114117](https://user-images.githubusercontent.com/68113972/102891195-12535d80-445e-11eb-8446-ef8918213d42.jpg)

![sc_20201222-114033](https://user-images.githubusercontent.com/68113972/102891234-213a1000-445e-11eb-9b6c-22be3dc83e30.jpg)

**Comment by dsarkar** [comment]
@Mtagxx,

Thank you for the information. 
- Regarding the issue that the risk encounter disappeared after updating to version 1.9.1, see https://github.com/corona-warn-app/cwa-app-ios/issues/1703. This is applicable also to Android devices.
- Regarding the BT issue, one more question: The last to screenshots, time 1140 and 1141 on your phone, can you let us know in detail how to reproduce this? Was it something like this: 
  -  Turn off BT, for a moment you still see the green card
  - after about a minute the green card turns white and CWA shows that risk assessment was stopped?

Thanks, DS

---
Corona-Warn-App Open Source Team

**Comment by icrf2000** [comment]
Hi!

For me, unfortunately, 1.9.1 does not yet solve the problem. I regret to say it... 

I disabled Bluetooth yesterday morning around 08:50 (the time I posted my last comment here) and had it disabled since then. Over te day, I occasionally checked the app. I always showed and now still shows (see screenshot)

1. "BLUETOOTH DEAKTIVIERT"
2. "Risiko-Ermittlung dauerhaft aktiv".

1 is correct. 2 is NOT correct and contradicts 1. I kind of wonder what makes this difficult to fix. Actually, the app is aware of the situation (Cf 1). So one would assume this information "only" needs to be applied correctly to the label 2.

![risk02](https://user-images.githubusercontent.com/11777822/102975791-e3da8e80-4500-11eb-9560-6207e32b827b.png)

**Comment by MikeMcC399** [comment]
@icrf2000 
There is a definition problem in what exposure logging active means. Does it only means:

- it is picking up Diagnosis Keys from the server, comparing them with keys on the device, calculating and displaying a risk evaluation

or does it include also:

- it is exchanging Bluetooth signals with other devices


If your device started with 
EXPOSURE LOGGING ACTIVE / RISIKO-ERMITTLUNG AKTIV, then you disabled Bluetooth, it will show
BLUETOOTH TURNED OFF / BLUETOOTH DEAKTIVIERT
in this state it will continue to do a risk analysis using the keys it has already stored on the device, however it cannot collect any new keys and therefore it cannot base its risk analysis on any new unrecorded encounters.

Now there is a difference in the text between the English and the German version.
You could say that the German text "Risiko-Ermittlung aktiv" is correct. Even though Bluetooth is disabled, it still continues to check for risks based on stored data (assuming the device has Internet connectivity of course).

The wording of the English text "Exposure Logging active" is inaccurate, because it is no longer logging any new keys if Bluetooth is switched off. The logging is actually inactive.

So there seems to be an implicit design decision that the Bluetooth status does not affect the historical recording of EXPOSURE LOGGING ACTIVE / RISIKO-ERMITTLUNG AKTIV. That should be reviewed to see whether the Bluetooth status should be taken into account. 

There are some other related discussions about the inaccurate display of how long exposure was active. See https://github.com/corona-warn-app/cwa-wishlist/issues/290.

**Comment by MikeMcC399** [comment]
PS CWA does know that there is a different status if Bluetooth is disabled.
If you tap on EXPOSURE LOGGING ACTIVE / RISIKO-ERMITTLUNG AKTIV
you will see

Exposure Logging
Restricted

or

Risiko-Ermittlung
Eingeschränkt

displayed in the detailed screen,

**Comment by Mtagxx** [comment]
Hello @dsarkar,

usually I have: 

- "Priorisierte Hintergundaktivität" aus, 
- BT off and 
- COVID-19-Benachrichtigungen off. 

When I opened CWA today at 13:06 I got the following picture (please compare it to yesterday 11:41 from my previous post):


![sc23_1](https://user-images.githubusercontent.com/68113972/103016737-d3e39e80-4542-11eb-898a-4bea38347bc4.jpg)



Then I switched COVID-19-Benachrichtigungen to on (in Einstellungen->Google->COVID-19):



![sc23_2](https://user-images.githubusercontent.com/68113972/103016906-1dcc8480-4543-11eb-8e1c-ddbc553aae54.jpg)

Then I closed CWA again., because one always has to open CWA twice to see something happen  :-)


Starting cwa again:
![sc23_3](https://user-images.githubusercontent.com/68113972/103017186-861b6600-4543-11eb-91ca-e6046f9084fe.jpg)


Finally I got:

![sc23_4](https://user-images.githubusercontent.com/68113972/103017237-99c6cc80-4543-11eb-9e32-fe88365da743.jpg)


Hope that helps! 
Merry Christmas!

Best regards
Chris

**Comment by dsarkar** [comment]
@Mtagxx, many thanks for the detailed information. We will forward this to the developers. Merry Christmas also to you!

**Comment by dsarkar** [comment]
@icrf2000, @MikeMcC399 Thanks also to you for your contributions. Info will be forwarded. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@dsarkar 
Happy Christmas to the Open Source Team!

As far as I remember, CWA will also show "Risiko-Ermittlung aktiv" even when the mobile device is switched off. I will check that out and open a new issue for that explicit point in a few days' time.

**Comment by dsarkar** [comment]
@MikeMcC399, Frohe Weihnachten! 
 
 ok, let's separate these two issues. I think there is no need for a new ticket. I reopened https://github.com/corona-warn-app/cwa-app-android/issues/929 just now. Maybe you can post your updates there, if applicable.

- BT disabled but CWA shows "Risiko-Ermittlung dauerhaft aktiv" https://github.com/corona-warn-app/cwa-app-android/issues/920
- Device off but CWA shows "Risiko-Ermittlung dauerhaft aktiv" https://github.com/corona-warn-app/cwa-app-android/issues/929 

I will create a separate JIRA ticket, both issues are currently handled in the same JIRA ticket currently. 

- I can reproduce the BT issue on a Samsung device, will post details shortly.
- Regarding the 'Device off' issue, will try to reproduce. 

DS

**Comment by dsarkar** [comment]
![image](https://user-images.githubusercontent.com/1409741/103085022-c977e200-45e0-11eb-9f47-6fd6175c7128.png)

**Comment by icrf2000** [comment]
Hello @dsarkar, on what device type did you create those screenshots? If my Samsung would behave like what you show ("Risikoermittlung war an X der letzten 14 Tage aktiv" instead of "Risiko-Ermittlung dauerhaft aktiv" as it currently does), I would say it is good and plausible. I admit that after @MikeMcC399's comment from yesterday ("There is a definition problem in what exposure logging active means...") I am no longer sure whether my expectation is simply wrong or there's really a wrong app behavior (limited to Samsung as it stands).

Anyway, I wish you and all the CWA/SAP/Telekom opensource team members as merry a Christmas as is possible given the circumstances! What you achieved is impressive!

**Comment by dsarkar** [comment]
@icrf2000 Merry Christmas to you as well! I will forward you wishes to other team mebers, thanks. 

I updated my post with more infomation.

**Comment by dsarkar** [comment]
@Mtagxx, thanks again. You use CWA 1.9.1. on Android 9, which device? Thanks.

**Comment by dsarkar** [comment]
For comparison:

![image](https://user-images.githubusercontent.com/1409741/103150322-3de28a80-4773-11eb-85f9-9c7b379c28ee.png)

**Comment by Mtagxx** [comment]
Hello @dsarkar ,
I'm using cwa version 1.9.1 with ENF Version 1820451600 on a Samsung Galaxy J3 (Modell SM-J330F).
Best regards
Chris

**Comment by dsarkar** [comment]
@Mtagxx, thanks for the additional details, forwarded to developers.

**Comment by dsarkar** [comment]
All reported devices here are SAMSUNG phones. Any feedback on other devices?

**Comment by daimpi** [comment]
@dsarkar if it helps I could test this on my 2nd Android device which is a Samsung tablet (Galaxy Tab S3). Lemme know if you want me to test this.

**Comment by dsarkar** [comment]
- @daimpi, yes, please, if you would be so kind and let me know what happens when you deactivate BT. Does the device immediately show "Risiko-Ermittlung gestoppt"? And then when you active BT again, does the green card come back? Thanks.

- The issue with (some?) Android device is apparently that it is not easy/impossible to track the time BT is on/off, i.e. one can't show x days of 14 days active. However, I have the impression, that Apple devices do not track that either, but show immediately "Risiko-Ermittlung gestoppt" on deactivating BT. Seems a different implementation alltegehter..

**Comment by daimpi** [comment]
@dsarkar ok I tested this yesterday and checked again today:

The green card didn't disappear when I disabled Bluetooth yesterday, but the "Bluetooth disabled" status was shown (replacing the "Risikoermittlung aktiv" status):
<img src="https://user-images.githubusercontent.com/22129968/103354256-5c19f480-4aab-11eb-918d-5a4199ef12eb.png" width="400">
I kept BT disabled the whole time but the counter nevertheless ticked up to "1 day active" today (up from "0 days active" yesterday):
<img src="https://user-images.githubusercontent.com/22129968/103354380-adc27f00-4aab-11eb-8c05-8faa5574ed84.png" width="400">

My device:
- Samsung Galaxy Tab S3 (SM-T820)
- Android 9
- CWA 1.9.1
- ENF 18204516000

**Comment by dsarkar** [comment]
@daimpi, thanks for info. Very different to the iOS implementation.

**Comment by MikeMcC399** [comment]
This issue is no longer relevant due to the changes made with the CWA 1.15.1 release.

https://www.coronawarn.app/en/blog/2021-03-24-corona-warn-app-version-1-15/ says:

"With version 1.15, the risk card without exposures no longer shows how long exposure logging was active. Instead, for the first 14 days after installation, the app shows the number of days since installation. After that, the line on the risk card will be removed. Of course, risk exposure is still active unless users turn their smartphone or Bluetooth off."

I think it should be possible to close this issue.

**Comment by dsarkar** [comment]
Hi @icrf2000, see https://github.com/corona-warn-app/cwa-app-android/issues/920#issuecomment-808453888. We suggest closing this issue. Thanks to everybody for contributing here. 
Best wishes, DS


---
Corona-Warn-App Open Source Team
