### ISSUE TITLE
If device is turned off, it is still counted as active exposure notification

### ISSUE THREAD

**Issue by dadosch** [corona-warn-app/cwa-app-android#929]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Describe the bug
If you turn on exposure notification, then turn of your device for some days, then turn it on again: it wrongly shows that EN was constantly on.

## Expected behaviour
If the device is turned off, it should probably be shown in the UI
## Steps to reproduce the issue

- turn on EN
- shut down phone for some days
- turn on phone
- see that it shows EN was constantly on

## Technical details

- Mobile device: LG H815
- Android version: Lineageos, Android 9

## Possible Fix
Maybe receive ACTION_SHUTDOWN intent, and set a flag that device was turned off.

## Additional context

---
Related: https://github.com/corona-warn-app/cwa-app-android/issues/920 

---
Internal Tracking ID: EXPOSUREAPP-1925
Related: EXPOSUREAPP-5170

**Comment by daimpi** [comment]
Related to: #920 

This seems to work distinctly different under iOS: https://github.com/corona-warn-app/cwa-documentation/issues/389

**Comment by heinezen** [comment]
Fixed in CWA version 1.5. Since there haven't been new reports in two months, I'll close this issue.

----
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Hi @dadosch, can you confirm that this issue still persists with CWA 1.9.1. Thanks, feedback very much appreciated. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by dadosch** [comment]
Hi @dsarkar . Yes, I can confirm this issue is still there in 1.9.1

**Comment by MikeMcC399** [comment]
@dsarkar 

I can also confirm:

## Repro steps
1. Install CWA
2. Activate Exposure Logging
3. Switch off mobile device
4. Wait 48 hours
5. Switch on mobile device
6. Wait 5 minutes
7. Open CWA and note risk card display
"Exposure logging was active for 2 of the past 14 days."

## Expected behaviour
Risk card should display
"Exposure logging was active for 0 of the past 14 days."
i.e. no days should be counted active for the time that the device was powered off, because if it was powered off then exposure logging could not have been active, neither through Bluetooth, nor through risk evaluation during this time.

## Environment
CWA Version: 1.9.1
ENF Version: 18204516000
Android Version: 8.0.0
Mobile device: Samsung Galaxy A5 (2017) SM-A520F

**Comment by dsarkar** [comment]
@dadosch, @MikeMcC399, Thanks for the feedback. We will forward this information to the developers. 

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Hi @dadosch, @MikeMcC39,

Thanks for the feedback. We will forward this information to the developers. 
Actually, seems somehow related to the BT issue, however. I have separated these two issues into two different internal tickets.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
This issue is no longer relevant with CWA 1.15.1.

According to the [announcement for Corona-Warn-App version 1.15](https://www.coronawarn.app/en/blog/2021-03-24-corona-warn-app-version-1-15/):

"With version 1.15, the risk card without exposures no longer shows how long exposure logging was active. Instead, for the first 14 days after installation, the app shows the number of days since installation. After that, the line on the risk card will be removed. Of course, risk exposure is still active unless users turn their smartphone or Bluetooth off."

The original bug report said:

"If you turn on exposure notification, then turn of (sic) your device for some days, then turn it on again: it wrongly shows that EN was constantly on."

CWA no longer attempts to record and display how long the device was on.

---
It should now be possible to close this issue.

**Comment by dsarkar** [comment]
Dear @dadosch, see https://github.com/corona-warn-app/cwa-app-android/issues/929#issuecomment-808372174. We suggest closing this issue. Thanks for contributing here. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by dadosch** [comment]
Yes, fixed with the latest version :)
