### ISSUE TITLE
Android 11 ENS requirements

### ISSUE THREAD

**Issue by duchampdev** [corona-warn-app/cwa-app-android#986]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## description
According to Google, ENS does no longer require location services to be active in order to work, starting from Android 11 [1]. Thus, the CWA should not send a notification to Android 11 users when location services are deactivated. I have verified that the notification appears on a phone running Android 11, but still exposure logging seems to work fine (CWA indicates this).

I'm currently quite busy but can take care of this myself, probably next week. As Android 11 is not yet officially published and the app's core functionality is most likely not affected, I'd say this is not time critical for now.

[1] https://blog.google/inside-google/company-announcements/update-exposure-notifications/

---
Internal Tracking ID: EXPOSUREAPP-2050

**Comment by duchampdev** [comment]
@GPclips @JoachimFritsch Does the assignment and transfer to JIRA indicate, that you'll take care of it internally or shall I work on it?

**Comment by GPclips** [comment]
Hello @duchampdev,

we added this to our internal JIRA and informed, as well as assigned the bug, to our dev team.
We will start working on it as soon as possible.

Thanks for asking,
LMM

Corona-Warn-App Open Source Team

**Comment by MikeJayDee** [comment]
Just to confirm that as expected, the issue as described by @duchampdev for Android 11 Beta is also still applicable to the final version of Android 11 (tested on Pixel 2) and the current CWA version (1.3.1).

**Comment by duchampdev** [comment]
I just realized that this has been resolved in the meantime: https://github.com/corona-warn-app/cwa-app-android/pull/1057

**Comment by MikeJayDee** [comment]
The onboarding screen on a clean install on Android 11 still shows a card that location services need to be activated ("Standortverwendung erlauben"). This card should not be displayed on Android 11:
![Screenshot_20201019-152409](https://user-images.githubusercontent.com/65447797/96459376-5a69c000-1222-11eb-84d5-b006f715079d.png)

**Comment by daimpi** [comment]
@duchampdev @MikeJayDee I think we should either

a) reopen this issue, to signify that it's not resolved 
or
b) move the problem @MikeJayDee discovered into a new separate issue.

What do you think?

**Comment by loki-cui** [comment]
@svengabr

**Comment by BMItter** [comment]
@MikeJayDee @svengabr @duchampdev 
The provided text has a lack of information. Showing ([...]until Android 11) or not showing the Card would be better (but here are edgecases for different Beta-Versions of Android 11 when to show the card and when not). 
I reported this UI issue and there will probably be a better in-app information flow in the future.
Thanks for reporting!

As this issue doesn't effect the core function (locationless scanning under Android 11) issue stays closed.
